import type { Metadata } from 'next'
import { siteConfig } from '@/config/site'

export const metadata: Metadata = { title: 'Terms of Service' }

export default function TermsPage() {
  return (
    <div className="pt-14 min-h-screen bg-braun-50">
      <div className="max-w-3xl mx-auto px-6 py-20">
        <div className="text-[10px] font-mono uppercase tracking-widest text-braun-500 mb-6">
          Legal
        </div>
        <h1 className="text-3xl lg:text-4xl font-light tracking-tight text-braun-900 mb-4">
          Terms of Service
        </h1>
        <p className="text-[10px] font-mono text-braun-500 uppercase tracking-widest mb-12">
          Last updated: February 1, 2026
        </p>
        <div className="bg-white border border-braun-200 p-8 lg:p-12 space-y-8 text-sm text-braun-600 leading-relaxed">
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing, browsing, or using the {siteConfig.name} platform (the &quot;Service&quot;), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service (the &quot;Terms&quot;). These Terms constitute a legally binding agreement between you (or the organization you represent) and {siteConfig.name}. If you do not agree to these Terms, you must not access or use the Service.</p>
            <p className="mt-3">If you are using the Service on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms. In such cases, &quot;you&quot; and &quot;your&quot; refer to that organization. You further represent that you are at least 18 years of age and are legally capable of entering into binding contracts in your jurisdiction.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">2. Service Description</h2>
            <p>{siteConfig.name} provides a process intelligence platform that includes process discovery, conformance checking, real-time monitoring, root cause analysis, custom dashboards, and workflow automation (the &quot;Service&quot;). The specific features, capacity limits, and support levels available to you depend on the plan tier you subscribe to — Free, Pro, or Enterprise — as described on our pricing page.</p>
            <p className="mt-3">We continuously improve the Service and may add, modify, or discontinue features from time to time. For material changes that reduce core functionality of a paid plan, we will provide at least 30 days&apos; advance notice. The Free tier is provided as-is and may be modified or discontinued at any time without prior notice. We reserve the right to introduce new plan tiers or adjust pricing for future subscription periods with 30 days&apos; notice.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">3. Account Registration & Security</h2>
            <p>To use {siteConfig.name}, you must register for an account by providing accurate, current, and complete information. You agree to keep your account information up to date at all times. {siteConfig.name} reserves the right to suspend or terminate accounts that contain materially inaccurate or fraudulent information.</p>
            <p className="mt-3">You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. We strongly recommend enabling two-factor authentication (2FA), which is available on all plans and required on Enterprise plans. You must notify {siteConfig.name} immediately at <a href={`mailto:${siteConfig.email}`} className="text-braun-900 underline hover:text-braun-orange transition-colors">{siteConfig.email}</a> if you become aware of any unauthorized access to your account. {siteConfig.name} will not be liable for any loss or damage arising from your failure to maintain the security of your account credentials.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">4. Your Data & Intellectual Property</h2>
            <p>You retain all rights, title, and interest in and to the data you upload to {siteConfig.name} (&quot;Your Data&quot;). {siteConfig.name} does not claim ownership of Your Data. By using the Service, you grant {siteConfig.name} a limited, non-exclusive, worldwide license to process, store, and display Your Data solely as necessary to provide and improve the Service in accordance with these Terms and our Privacy Policy.</p>
            <p className="mt-3">All intellectual property rights in the {siteConfig.name} platform — including its software, algorithms, user interface, documentation, and trademarks — remain the exclusive property of {siteConfig.name}. Nothing in these Terms grants you any right, title, or interest in the Service beyond the limited usage rights expressly provided herein.</p>
            <p className="mt-3">If you provide feedback, suggestions, or ideas about the Service (&quot;Feedback&quot;), you grant {siteConfig.name} an irrevocable, perpetual, royalty-free, worldwide license to use, modify, and incorporate such Feedback into the Service without any obligation or compensation to you. You acknowledge that Feedback is provided voluntarily and does not create any confidentiality obligation for {siteConfig.name}.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">5. Acceptable Use Policy</h2>
            <p>You agree to use {siteConfig.name} only for lawful purposes and in compliance with all applicable local, national, and international laws and regulations. Permitted uses include uploading and analyzing event logs from your own systems, building process models and dashboards, configuring automation workflows, and accessing the platform via our API in accordance with published rate limits and documentation.</p>
            <p className="mt-3">You may not: (a) use the Service to process data that you do not have the right to process; (b) upload content that is unlawful, harmful, threatening, abusive, or otherwise objectionable; (c) attempt to reverse-engineer, decompile, or disassemble any part of the platform; (d) circumvent usage limits, rate limits, or access controls; (e) use the Service to develop a competing product or service; (f) resell, sublicense, or redistribute access to the Service without prior written consent; or (g) interfere with or disrupt the integrity or performance of the Service or its underlying infrastructure.</p>
            <p className="mt-3">API usage is subject to rate limits as published in our developer documentation. Sustained abuse of rate limits may result in temporary throttling or, in repeated cases, account suspension. We reserve the right to investigate and take appropriate action — including suspension or termination — against any user who violates this Acceptable Use Policy.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">6. Payment & Billing</h2>
            <p>Paid subscriptions are billed in advance on a monthly or annual basis, depending on the billing cycle you select at the time of purchase. Annual subscriptions receive a discounted per-seat rate as listed on our pricing page. All fees are quoted in US Dollars unless otherwise specified in an Enterprise agreement. Prices are exclusive of applicable taxes, levies, and duties, which will be added to your invoice as required by law.</p>
            <p className="mt-3">You authorize {siteConfig.name} to charge your designated payment method for all applicable fees. If a payment fails, we will attempt to charge your payment method up to three additional times over a 10-day period. If payment remains unsuccessful, your account may be downgraded to the Free tier, and access to paid features will be restricted. Outstanding balances accrue interest at the rate of 1.5% per month (or the maximum rate permitted by law, whichever is lower).</p>
            <p className="mt-3">You may upgrade or downgrade your plan at any time from your account settings. Upgrades take effect immediately, and you will be charged a prorated amount for the remainder of your current billing cycle. Downgrades take effect at the end of your current billing cycle. No refunds are provided for partial billing periods, except as required by applicable law or as specified in an Enterprise agreement.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">7. Service Level Agreement</h2>
            <p>{siteConfig.name} commits to the following uptime targets, measured as monthly availability of the core platform (excluding scheduled maintenance): Free tier — no uptime guarantee; Pro plans — 99.5% monthly uptime; Enterprise plans — 99.9% monthly uptime (or as specified in your service agreement). Uptime is measured by our external monitoring systems and excludes planned maintenance windows.</p>
            <p className="mt-3">If {siteConfig.name} fails to meet the applicable uptime target for a given month, affected paid customers are eligible for service credits. Pro plan customers receive a credit equal to 10% of their monthly fee for each full percentage point below the target. Enterprise plan customers receive credits as defined in their service agreement, typically 10% per percentage point up to a maximum of 30% of the monthly fee. Credits must be requested within 30 days of the downtime event and are applied to future invoices — they are not redeemable for cash.</p>
            <p className="mt-3">The SLA does not apply to: (a) scheduled maintenance communicated at least 72 hours in advance; (b) downtime caused by factors outside our reasonable control, including force majeure events, internet connectivity issues, or your equipment failures; (c) features labeled as &quot;beta&quot; or &quot;preview&quot;; or (d) service disruptions resulting from your actions or your violation of these Terms. Scheduled maintenance windows are typically performed during low-traffic periods (Sundays 02:00-06:00 UTC) and are communicated via email and the {siteConfig.name} status page.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">8. Limitation of Liability</h2>
            <p>To the maximum extent permitted by applicable law, {siteConfig.name}&apos;s total aggregate liability to you for all claims arising out of or related to these Terms or the Service — whether in contract, tort (including negligence), strict liability, or any other legal theory — shall not exceed the total fees you paid to {siteConfig.name} during the twelve (12) months immediately preceding the event giving rise to the claim. For users on the Free tier, {siteConfig.name}&apos;s aggregate liability shall not exceed fifty US dollars ($50).</p>
            <p className="mt-3">In no event shall {siteConfig.name} be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenue, data, goodwill, or business opportunity, regardless of whether such damages were foreseeable and whether or not {siteConfig.name} was advised of the possibility of such damages. This limitation applies to all causes of action in the aggregate, including breach of contract, breach of warranty, negligence, and other torts.</p>
            <p className="mt-3">The foregoing limitations do not apply to: (a) {siteConfig.name}&apos;s indemnification obligations under Section 10; (b) {siteConfig.name}&apos;s gross negligence or willful misconduct; (c) any liability that cannot be excluded or limited under applicable law; or (d) breaches of confidentiality obligations related to Your Data. Some jurisdictions do not allow the exclusion or limitation of certain damages, so certain limitations above may not apply to you.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">9. Warranties & Disclaimers</h2>
            <p>The Free tier of the Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, whether express, implied, statutory, or otherwise. {siteConfig.name} expressly disclaims all implied warranties, including warranties of merchantability, fitness for a particular purpose, title, and non-infringement with respect to the Free tier.</p>
            <p className="mt-3">For paid plans, {siteConfig.name} warrants that the Service will perform materially in accordance with the applicable documentation during the subscription term. If the Service fails to conform to this warranty, your exclusive remedy and {siteConfig.name}&apos;s sole obligation shall be, at {siteConfig.name}&apos;s option, to: (a) use commercially reasonable efforts to correct the non-conformity; or (b) terminate your subscription and provide a pro-rata refund of prepaid fees for the unused portion of the subscription term.</p>
            <p className="mt-3">{siteConfig.name} does not warrant that the Service will be uninterrupted, error-free, or completely secure. No advice or information, whether oral or written, obtained from {siteConfig.name} or through the Service shall create any warranty not expressly stated in these Terms. You acknowledge that you use the Service at your own risk and that {siteConfig.name} is not responsible for the accuracy, completeness, or reliability of any output generated by the platform based on your input data.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">10. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless {siteConfig.name} and its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&apos; fees) arising out of or related to: (a) your use of the Service in violation of these Terms; (b) your violation of any applicable law or regulation; (c) your infringement of any third party&apos;s intellectual property or other rights; or (d) any data you upload to the Service that causes harm to a third party.</p>
            <p className="mt-3">{siteConfig.name} agrees to indemnify, defend, and hold harmless you from and against any third-party claim that the Service, as provided by {siteConfig.name} and used in accordance with these Terms, infringes any valid patent, copyright, or trademark of a third party. If the Service becomes or is likely to become the subject of an infringement claim, {siteConfig.name} may, at its option: (a) obtain the right for you to continue using the Service; (b) modify the Service so that it is no longer infringing; or (c) terminate your subscription and provide a pro-rata refund of prepaid fees.</p>
            <p className="mt-3">The indemnification obligations in this section are subject to the indemnified party: (a) promptly notifying the indemnifying party in writing of the claim; (b) granting the indemnifying party sole control of the defense and settlement; and (c) providing reasonable cooperation in the defense at the indemnifying party&apos;s expense. The indemnifying party may not settle any claim in a manner that imposes obligations on the indemnified party without prior written consent.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">11. Termination & Suspension</h2>
            <p><strong className="text-braun-900">Termination for convenience:</strong> You may terminate your {siteConfig.name} account at any time from your account settings. For monthly subscriptions, termination takes effect at the end of the current billing period. For annual subscriptions, termination takes effect at the end of the current annual term, and no refund is provided for the remaining period unless otherwise specified in an Enterprise agreement. {siteConfig.name} may terminate the Free tier or any free account at any time with 30 days&apos; prior notice.</p>
            <p className="mt-3"><strong className="text-braun-900">Termination for cause:</strong> Either party may terminate these Terms immediately upon written notice if the other party: (a) materially breaches these Terms and fails to cure the breach within 30 days of receiving written notice; (b) becomes insolvent, files for bankruptcy, or has a receiver appointed for a substantial part of its assets; or (c) ceases to operate in the ordinary course of business. {siteConfig.name} may also immediately suspend or terminate your access if your use poses a security risk to the platform, other users, or third parties.</p>
            <p className="mt-3"><strong className="text-braun-900">Effect of termination:</strong> Upon termination, your right to access the Service ceases immediately (or at the end of the applicable billing period for termination for convenience). {siteConfig.name} will make Your Data available for export for a period of 30 days following termination, after which it will be permanently deleted in accordance with our data retention policy. The following sections survive termination: Sections 4 (Your Data & IP), 8 (Limitation of Liability), 9 (Warranties & Disclaimers), 10 (Indemnification), 12 (Governing Law), and 14 (General Provisions).</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">12. Governing Law & Dispute Resolution</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law principles. Any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be resolved through binding arbitration administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules.</p>
            <p className="mt-3">The arbitration shall be conducted by a single arbitrator in Wilmington, Delaware (or remotely by mutual agreement). The arbitrator&apos;s decision shall be final and binding, and judgment on the award may be entered in any court of competent jurisdiction. Each party shall bear its own costs and attorneys&apos; fees, unless the arbitrator determines that a party&apos;s claim or defense was frivolous, in which case the arbitrator may award costs and fees to the prevailing party.</p>
            <p className="mt-3"><strong className="text-braun-900">Class action waiver:</strong> You agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action. If for any reason a claim proceeds in court rather than in arbitration, both parties waive the right to a jury trial. Notwithstanding the foregoing, either party may seek injunctive or equitable relief in any court of competent jurisdiction to protect its intellectual property rights or confidential information. Claims within the jurisdiction of small claims court may be filed there instead of arbitration.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">13. Modifications to Terms</h2>
            <p>{siteConfig.name} reserves the right to modify these Terms at any time. When we make material changes, we will provide at least 30 days&apos; advance notice by sending an email to the address associated with your account and by posting a notice on the {siteConfig.name} dashboard. The updated Terms will include a revised &quot;Last updated&quot; date at the top of this page.</p>
            <p className="mt-3">Your continued use of the Service after the effective date of any modification constitutes your acceptance of the updated Terms. If you do not agree with the modified Terms, you must stop using the Service and terminate your account before the changes take effect. For Enterprise customers with executed service agreements, any conflict between these Terms and your service agreement shall be resolved in favor of the service agreement.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">14. General Provisions</h2>
            <p><strong className="text-braun-900">Entire agreement:</strong> These Terms, together with our Privacy Policy and any applicable service agreements or order forms, constitute the entire agreement between you and {siteConfig.name} regarding the Service and supersede all prior or contemporaneous communications, proposals, and agreements, whether oral or written. <strong className="text-braun-900">Severability:</strong> If any provision of these Terms is found to be invalid or unenforceable by a court of competent jurisdiction, that provision shall be enforced to the maximum extent permissible, and the remaining provisions shall remain in full force and effect.</p>
            <p className="mt-3"><strong className="text-braun-900">Waiver:</strong> The failure of {siteConfig.name} to enforce any right or provision of these Terms shall not constitute a waiver of that right or provision. Any waiver must be in writing and signed by an authorized representative of {siteConfig.name}. <strong className="text-braun-900">Assignment:</strong> You may not assign or transfer these Terms or your rights hereunder without {siteConfig.name}&apos;s prior written consent. {siteConfig.name} may assign these Terms freely in connection with a merger, acquisition, reorganization, or sale of all or substantially all of its assets.</p>
            <p className="mt-3"><strong className="text-braun-900">Force majeure:</strong> Neither party shall be liable for any failure or delay in performance due to circumstances beyond its reasonable control, including natural disasters, acts of war or terrorism, epidemics, government actions, power failures, internet disturbances, or telecommunications failures. The affected party must provide prompt written notice and use commercially reasonable efforts to mitigate the impact. If a force majeure event continues for more than 60 days, either party may terminate the affected portion of the agreement upon written notice.</p>
          </section>
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-braun-900 mb-3">15. Contact</h2>
            <p>If you have questions about these Terms or need to send a legal notice, please contact us at <a href={`mailto:${siteConfig.legalEmail}`} className="text-braun-900 underline hover:text-braun-orange transition-colors">{siteConfig.legalEmail}</a>. For general support inquiries, contact <a href={`mailto:${siteConfig.email}`} className="text-braun-900 underline hover:text-braun-orange transition-colors">{siteConfig.email}</a>.</p>
            <p className="mt-3">{siteConfig.name} legal notices should be sent to: {siteConfig.name}, Attn: Legal Department, 251 Little Falls Drive, Wilmington, DE 19808, United States. We will make commercially reasonable efforts to respond to all legal inquiries within ten (10) business days.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
